//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NetMessage.proto
namespace NetMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KNMActiveSkillData")]
  public partial class KNMActiveSkillData : global::ProtoBuf.IExtensible
  {
    public KNMActiveSkillData() {}
    
    private uint _SkillID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }
    private uint _SkillLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SkillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillLevel
    {
      get { return _SkillLevel; }
      set { _SkillLevel = value; }
    }
    private uint _SkillExp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SkillExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillExp
    {
      get { return _SkillExp; }
      set { _SkillExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KNMPassiveSkillData")]
  public partial class KNMPassiveSkillData : global::ProtoBuf.IExtensible
  {
    public KNMPassiveSkillData() {}
    
    private uint _SkillID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillID
    {
      get { return _SkillID; }
      set { _SkillID = value; }
    }
    private uint _SkillLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SkillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillLevel
    {
      get { return _SkillLevel; }
      set { _SkillLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KNMSkillDataList")]
  public partial class KNMSkillDataList : global::ProtoBuf.IExtensible
  {
    public KNMSkillDataList() {}
    
    private readonly global::System.Collections.Generic.List<KNMActiveSkillData> _ActiveSkillData = new global::System.Collections.Generic.List<KNMActiveSkillData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ActiveSkillData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<KNMActiveSkillData> ActiveSkillData
    {
      get { return _ActiveSkillData; }
    }
  
    private readonly global::System.Collections.Generic.List<KNMPassiveSkillData> _PassiveSkillData = new global::System.Collections.Generic.List<KNMPassiveSkillData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PassiveSkillData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<KNMPassiveSkillData> PassiveSkillData
    {
      get { return _PassiveSkillData; }
    }
  
    private uint _SkillPoint;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SkillPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillPoint
    {
      get { return _SkillPoint; }
      set { _SkillPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KNMAcceptQuest")]
  public partial class KNMAcceptQuest : global::ProtoBuf.IExtensible
  {
    public KNMAcceptQuest() {}
    
    private uint _QuestID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"QuestID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint QuestID
    {
      get { return _QuestID; }
      set { _QuestID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _QuestValue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"QuestValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> QuestValue
    {
      get { return _QuestValue; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KNMQuestDataList")]
  public partial class KNMQuestDataList : global::ProtoBuf.IExtensible
  {
    public KNMQuestDataList() {}
    
    private byte[] _QuestStateList;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"QuestStateList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] QuestStateList
    {
      get { return _QuestStateList; }
      set { _QuestStateList = value; }
    }
    private readonly global::System.Collections.Generic.List<KNMAcceptQuest> _AcceptedQuestList = new global::System.Collections.Generic.List<KNMAcceptQuest>();
    [global::ProtoBuf.ProtoMember(2, Name=@"AcceptedQuestList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<KNMAcceptQuest> AcceptedQuestList
    {
      get { return _AcceptedQuestList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KNMBagItemPositionDataList")]
  public partial class KNMBagItemPositionDataList : global::ProtoBuf.IExtensible
  {
    public KNMBagItemPositionDataList() {}
    
    private readonly global::System.Collections.Generic.List<int> _ItemPositionList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ItemPositionList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> ItemPositionList
    {
      get { return _ItemPositionList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}